version: "3.3"
networks:
  tower-defense:
    name: "network-elastic"
    driver_opts:
      icc: "true"
    driver: bridge

services:
  # ElasticSearch
  elasticsearch1:
    container_name: elasticsearch_node1
    hostname: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - "node.name=elasticsearch1"
      - ELASTIC_PASSWORD=dangtuan12
      - "cluster.name=es-cluster"
      - "transport.host=0.0.0.0"
      - "transport.tcp.port=9300"
      - "discovery.seed_hosts=elasticsearch2,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms1512m -Xmx1512m"
      - xpack.security.enabled=true
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - xpack.security.authc.api_key.enabled=true
      - path.data=/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  elasticsearch2:
    container_name: elasticsearch_node2
    hostname: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - "node.name=elasticsearch2"
      - ELASTIC_PASSWORD=dangtuan12
      - "cluster.name=es-cluster"
      - "transport.host=0.0.0.0"
      - "transport.tcp.port=9300"
      - "discovery.seed_hosts=elasticsearch1,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms1512m -Xmx1512m"
      - xpack.security.enabled=true
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - xpack.security.authc.api_key.enabled=true
      - path.data=/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data2:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9202"]
      interval: 30s
      timeout: 10s
      retries: 30

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200
      - 9302:9300
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  elasticsearch3:
    container_name: elasticsearch_node3
    hostname: elasticsearch3
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - "node.name=elasticsearch3"
      - ELASTIC_PASSWORD=dangtuan12
      - "cluster.name=es-cluster"
      - "transport.host=0.0.0.0"
      - "transport.tcp.port=9300"
      - "discovery.seed_hosts=elasticsearch2,elasticsearch1"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms1512m -Xmx1512m"
      - xpack.security.enabled=true
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - xpack.security.authc.api_key.enabled=true
      - path.data=/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data3:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9203"]
      interval: 30s
      timeout: 10s
      retries: 30

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9203:9200
      - 9303:9300
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Kibana Service 
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="dangtuan12"
      - ELASTICSEARCH_URL=http://10.0.0.16:9200
      - SERVER_NAME=my-kibana
      - XPACK_SECURITY_ENABLED=true
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - ./kibana/data:/usr/share/kibana/data
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    # links:
    #   - elasticsearch:elasticsearch
    # depends_on:
    #   - elasticsearch
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Logstash Service        
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.17.10

    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD="dangtuan12"
      - NODE_NAME=my-logstash
      - XPACK_MONITORING_ENABLED=true
      # - "LS_JAVA_OPTS=-Xms8192m -Xmx8192m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    # links:
    #   - elasticsearch:elasticsearch
    # depends_on:
    #   - elasticsearch
    stdin_open: true
    tty: true
    networks:
      - tower-defense
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"






# curl -X PUT -u 'elastic:dangtuan12' http://localhost:9200/products